de.tavendo.autobahn.WampConnection Class Reference
de.tavendo.autobahn.WampConnection Class Reference
Classes
class CallMeta
RPC metadata.
class SubMeta
Event subscription metadata.
Public Member Functions
void connect (String wsUri, Wamp.ConnectionHandler sessionHandler)
void connect (String wsUri, Wamp.ConnectionHandler sessionHandler, WampOptions options)
Connect to server.
void call (String procUri, Class<?> resultType, CallHandler resultHandler, Object...arguments)
Issue a remote procedure call (RPC).
void call (String procUri, TypeReference<?> resultType, CallHandler resultHandler, Object...arguments)
Issue a remote procedure call (RPC).
void subscribe (String topicUri, Class<?> eventType, EventHandler eventHandler)
Subscribe to topic to receive events for.
void subscribe (String topicUri, TypeReference<?> eventType, EventHandler eventHandler)
Subscribe to topic to receive events for.
void unsubscribe (String topicUri)
Unsubscribe from topic.
void unsubscribe ()
Unsubscribe from any subscribed topic.
void prefix (String prefix, String uri)
Establish a prefix to be used in CURIEs.
void publish (String topicUri, Object event)
Publish an event to a topic.
Protected Member Functions
void createWriter ()
Create the connection transmitting leg writer.
void createReader ()
Create the connection receiving leg reader.
void processAppMessage (Object message)
Process WAMP messages coming from the background reader.
Protected Attributes
WampWriter mWriterHandler
The message handler of the background writer.
Private Member Functions
String newId (int len)
Create new random ID.
String newId ()
Create new random ID of default length.
void call (String procUri, CallMeta resultMeta, Object...arguments)
Issue a remote procedure call (RPC).
void subscribe (String topicUri, SubMeta meta)
Subscribe to topic to receive events for.
Private Attributes
final PrefixMap mOutgoingPrefixes = new PrefixMap()
Prefix map for outgoing messages.
final Random mRng = new Random()
RNG for IDs.
final ConcurrentHashMap
< String, CallMeta > mCalls = new ConcurrentHashMap<String, CallMeta>()
Metadata about issued, but not yet returned RPCs.
final ConcurrentHashMap
< String, SubMeta > mSubs = new ConcurrentHashMap<String, SubMeta>()
Metadata about active event subscriptions.
Wamp.ConnectionHandler mSessionHandler
The session handler provided to connect().
Static Private Attributes
static final boolean DEBUG = true
static final String TAG = WampConnection.class.getName()
static final char[] mBase64Chars
Set of chars to be used for IDs.
Detailed Description
Definition at line 29 of file WampConnection.java.
Member Function Documentation
void de.tavendo.autobahn.WampConnection.call (String procUri, CallMeta resultMeta, Object... arguments) [private]
Issue a remote procedure call (RPC).
Parameters:
procUri URI or CURIE of procedure to call.
resultMeta Call result metadata.
arguments Call arguments.
Definition at line 282 of file WampConnection.java.
References de.tavendo.autobahn.WebSocketWriter.forward(), de.tavendo.autobahn.WampConnection.mCalls, and de.tavendo.autobahn.WampConnection.newId().
Referenced by de.tavendo.autobahn.WampConnection.call().
void de.tavendo.autobahn.WampConnection.call (String procUri, Class<?> resultType, CallHandler resultHandler, Object... arguments)
Issue a remote procedure call (RPC).
This version should be used with primitive Java types and simple composite (class) types.
Parameters:
procUri URI or CURIE of procedure to call.
resultType Type we want the call result to be converted to.
resultHandler Call handler to process call result or error.
arguments Call arguments.
Implements de.tavendo.autobahn.Wamp.
Definition at line 302 of file WampConnection.java.
References de.tavendo.autobahn.WampConnection.call().
void de.tavendo.autobahn.WampConnection.call (String procUri, TypeReference<?> resultType, CallHandler resultHandler, Object... arguments)
Issue a remote procedure call (RPC).
This version should be used with result types which are containers, i.e. List<> or Map<>.
Parameters:
procUri URI or CURIE of procedure to call.
resultType Type we want the call result to be converted to.
resultHandler Call handler to process call result or error.
arguments Call arguments.
Implements de.tavendo.autobahn.Wamp.
Definition at line 317 of file WampConnection.java.
References de.tavendo.autobahn.WampConnection.call().
void de.tavendo.autobahn.WampConnection.connect (String wsUri, Wamp.ConnectionHandler sessionHandler, WampOptions options)
Connect to server.
Parameters:
wsUri WebSockets server URI.
sessionHandler The session handler to fire callbacks on.
Definition at line 180 of file WampConnection.java.
References de.tavendo.autobahn.PrefixMap.clear(), de.tavendo.autobahn.WebSocket.ConnectionHandler.CLOSE_CANNOT_CONNECT, de.tavendo.autobahn.WampConnection.mCalls, de.tavendo.autobahn.WampConnection.mOutgoingPrefixes, de.tavendo.autobahn.WampConnection.mSessionHandler, and de.tavendo.autobahn.WampConnection.mSubs.
void de.tavendo.autobahn.WampConnection.createReader () [protected]
Create the connection receiving leg reader.
Reimplemented from de.tavendo.autobahn.WebSocketConnection.
Definition at line 128 of file WampConnection.java.
References de.tavendo.autobahn.WampConnection.mCalls, and de.tavendo.autobahn.WampConnection.mSubs.
void de.tavendo.autobahn.WampConnection.createWriter () [protected]
Create the connection transmitting leg writer.
Reimplemented from de.tavendo.autobahn.WebSocketConnection.
Definition at line 115 of file WampConnection.java.
String de.tavendo.autobahn.WampConnection.newId (int len) [private]
Create new random ID.
This is used, i.e. for use in RPC calls to correlate call message with result message.
Parameters:
len Length of ID.
Returns:
New random ID of given length.
Definition at line 143 of file WampConnection.java.
References de.tavendo.autobahn.WampConnection.mBase64Chars, and de.tavendo.autobahn.WampConnection.mRng.
String de.tavendo.autobahn.WampConnection.newId () [private]
Create new random ID of default length.
Returns:
New random ID of default length.
Definition at line 157 of file WampConnection.java.
Referenced by de.tavendo.autobahn.WampConnection.call().
void de.tavendo.autobahn.WampConnection.prefix (String prefix, String uri)
Establish a prefix to be used in CURIEs.
Parameters:
prefix The prefix to be used in CURIEs.
uri The full URI this prefix shall resolve to.
Implements de.tavendo.autobahn.Wamp.
Definition at line 404 of file WampConnection.java.
References de.tavendo.autobahn.WebSocketWriter.forward(), de.tavendo.autobahn.PrefixMap.get(), de.tavendo.autobahn.WampConnection.mOutgoingPrefixes, and de.tavendo.autobahn.PrefixMap.set().
void de.tavendo.autobahn.WampConnection.processAppMessage (Object message) [protected]
Process WAMP messages coming from the background reader.
Reimplemented from de.tavendo.autobahn.WebSocketConnection.
Definition at line 226 of file WampConnection.java.
References de.tavendo.autobahn.WampConnection.mCalls, de.tavendo.autobahn.WampConnection.SubMeta.mEventHandler, de.tavendo.autobahn.WampConnection.CallMeta.mResultHandler, de.tavendo.autobahn.WampConnection.mSubs, de.tavendo.autobahn.Wamp.CallHandler.onError(), de.tavendo.autobahn.Wamp.EventHandler.onEvent(), and de.tavendo.autobahn.Wamp.CallHandler.onResult().
void de.tavendo.autobahn.WampConnection.publish (String topicUri, Object event)
Publish an event to a topic.
Parameters:
topicUri URI or CURIE of topic to publish event on.
event Event to be published.
Implements de.tavendo.autobahn.Wamp.
Definition at line 424 of file WampConnection.java.
References de.tavendo.autobahn.WebSocketWriter.forward(), de.tavendo.autobahn.WampConnection.mOutgoingPrefixes, and de.tavendo.autobahn.PrefixMap.shrink().
void de.tavendo.autobahn.WampConnection.subscribe (String topicUri, SubMeta meta) [private]
Subscribe to topic to receive events for.
Parameters:
topicUri URI or CURIE of topic to subscribe to.
meta Subscription metadata.
Definition at line 329 of file WampConnection.java.
References de.tavendo.autobahn.WebSocketWriter.forward(), de.tavendo.autobahn.WampConnection.mOutgoingPrefixes, de.tavendo.autobahn.WampConnection.mSubs, de.tavendo.autobahn.PrefixMap.resolveOrPass(), and de.tavendo.autobahn.PrefixMap.shrink().
Referenced by de.tavendo.autobahn.WampConnection.subscribe().
void de.tavendo.autobahn.WampConnection.subscribe (String topicUri, Class<?> eventType, EventHandler eventHandler)
Subscribe to topic to receive events for.
This version should be used with result types which are containers, i.e. List<> or Map<>.
Parameters:
topicUri URI or CURIE of topic to subscribe to.
eventType The type we want events to be converted to.
eventHandler The event handler to process received events.
Implements de.tavendo.autobahn.Wamp.
Definition at line 350 of file WampConnection.java.
References de.tavendo.autobahn.WampConnection.subscribe().
void de.tavendo.autobahn.WampConnection.subscribe (String topicUri, TypeReference<?> eventType, EventHandler eventHandler)
Subscribe to topic to receive events for.
This version should be used with primitive Java types and simple composite (class) types.
Parameters:
topicUri URI or CURIE of topic to subscribe to.
eventType The type we want events to be converted to.
eventHandler The event handler to process received events.
Implements de.tavendo.autobahn.Wamp.
Definition at line 364 of file WampConnection.java.
References de.tavendo.autobahn.WampConnection.subscribe().
void de.tavendo.autobahn.WampConnection.unsubscribe (String topicUri)
Unsubscribe from topic.
Parameters:
topicUri URI or CURIE of topic to unsubscribe from.
Implements de.tavendo.autobahn.Wamp.
Definition at line 375 of file WampConnection.java.
References de.tavendo.autobahn.WebSocketWriter.forward(), and de.tavendo.autobahn.WampConnection.mSubs.
void de.tavendo.autobahn.WampConnection.unsubscribe ()
Unsubscribe from any subscribed topic.
Implements de.tavendo.autobahn.Wamp.
Definition at line 388 of file WampConnection.java.
References de.tavendo.autobahn.WebSocketWriter.forward(), and de.tavendo.autobahn.WampConnection.mSubs.
Member Data Documentation
final char [] de.tavendo.autobahn.WampConnection.mBase64Chars [static, private]
Initial value:
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
         .toCharArray()
Set of chars to be used for IDs.
Definition at line 45 of file WampConnection.java.
Referenced by de.tavendo.autobahn.WampConnection.newId().
final ConcurrentHashMap<String, CallMeta> de.tavendo.autobahn.WampConnection.mCalls = new ConcurrentHashMap<String, CallMeta>() [private]
Metadata about issued, but not yet returned RPCs.
Definition at line 76 of file WampConnection.java.
Referenced by de.tavendo.autobahn.WampConnection.call(), de.tavendo.autobahn.WampConnection.connect(), de.tavendo.autobahn.WampConnection.createReader(), and de.tavendo.autobahn.WampConnection.processAppMessage().
final PrefixMap de.tavendo.autobahn.WampConnection.mOutgoingPrefixes = new PrefixMap() [private]
Prefix map for outgoing messages.
Definition at line 39 of file WampConnection.java.
Referenced by de.tavendo.autobahn.WampConnection.connect(), de.tavendo.autobahn.WampConnection.prefix(), de.tavendo.autobahn.WampConnection.publish(), and de.tavendo.autobahn.WampConnection.subscribe().
final Random de.tavendo.autobahn.WampConnection.mRng = new Random() [private]
RNG for IDs.
Definition at line 42 of file WampConnection.java.
Referenced by de.tavendo.autobahn.WampConnection.newId().
Wamp.ConnectionHandler de.tavendo.autobahn.WampConnection.mSessionHandler [private]
The session handler provided to connect().
Definition at line 109 of file WampConnection.java.
Referenced by de.tavendo.autobahn.WampConnection.connect().
final ConcurrentHashMap<String, SubMeta> de.tavendo.autobahn.WampConnection.mSubs = new ConcurrentHashMap<String, SubMeta>() [private]
Metadata about active event subscriptions.
Definition at line 106 of file WampConnection.java.
Referenced by de.tavendo.autobahn.WampConnection.connect(), de.tavendo.autobahn.WampConnection.createReader(), de.tavendo.autobahn.WampConnection.processAppMessage(), de.tavendo.autobahn.WampConnection.subscribe(), and de.tavendo.autobahn.WampConnection.unsubscribe().
WampWriter de.tavendo.autobahn.WampConnection.mWriterHandler [protected]
The message handler of the background writer.
Definition at line 36 of file WampConnection.java.
The documentation for this class was generated from the following file:
src/de/tavendo/autobahn/WampConnection.java