de.tavendo.autobahn.WebSocketWriter Class Reference
de.tavendo.autobahn.WebSocketWriter Class Reference
WebSocket writer, the sending leg of a WebSockets connection.
Public Member Functions
WebSocketWriter (Looper looper, Handler master, SocketChannel socket, WebSocketOptions options)
Create new WebSockets background writer.
void forward (Object message)
Call this from the foreground (UI) thread to make the writer (running on background thread) send a WebSocket message on the underlying TCP.
void handleMessage (Message msg)
Process message received from foreground thread.
Protected Member Functions
void sendFrame (int opcode, boolean fin, byte[] payload) throws IOException
Sends a WebSockets frame.
void sendFrame (int opcode, boolean fin, byte[] payload, int offset, int length) throws IOException
Sends a WebSockets frame.
void processMessage (Object msg) throws IOException, WebSocketException
Process WebSockets or control message from master.
void processAppMessage (Object msg) throws WebSocketException, IOException
Process message other than plain WebSockets or control message.
Private Member Functions
void notify (Object message)
Notify the master (foreground thread).
String newHandshakeKey ()
Create new key for WebSockets handshake.
byte[] newFrameMask ()
Create new (random) frame mask.
void sendClientHandshake (WebSocketMessage.ClientHandshake message) throws IOException
Send WebSocket client handshake.
void sendClose (WebSocketMessage.Close message) throws IOException, WebSocketException
Send WebSockets close.
void sendPing (WebSocketMessage.Ping message) throws IOException, WebSocketException
Send WebSockets ping.
void sendPong (WebSocketMessage.Pong message) throws IOException, WebSocketException
Send WebSockets pong.
void sendBinaryMessage (WebSocketMessage.BinaryMessage message) throws IOException, WebSocketException
Send WebSockets binary message.
void sendTextMessage (WebSocketMessage.TextMessage message) throws IOException, WebSocketException
Send WebSockets text message.
void sendRawTextMessage (WebSocketMessage.RawTextMessage message) throws IOException, WebSocketException
Send WebSockets binary message.
Private Attributes
final Random mRng = new Random()
Random number generator for handshake key and frame mask generation.
final Handler mMaster
Connection master.
final Looper mLooper
Message looper this object is running on.
final SocketChannel mSocket
The NIO socket channel created on foreground thread.
final WebSocketOptions mOptions
WebSockets options.
final ByteBufferOutputStream mBuffer
The send buffer that holds data to send on socket.
Static Private Attributes
static final boolean DEBUG = true
static final String TAG = WebSocketWriter.class.getName()
Detailed Description
WebSocket writer, the sending leg of a WebSockets connection.
This is run on it's background thread with it's own message loop. The only method that needs to be called (from foreground thread) is forward(), which is used to forward a WebSockets message to this object (running on background thread) so that it can be formatted and sent out on the underlying TCP socket.
Definition at line 39 of file WebSocketWriter.java.
Constructor & Destructor Documentation
de.tavendo.autobahn.WebSocketWriter.WebSocketWriter (Looper looper, Handler master, SocketChannel socket, WebSocketOptions options)
Create new WebSockets background writer.
Parameters:
looper The message looper of the background thread on which this object is running.
master The message handler of master (foreground thread).
socket The socket channel created on foreground thread.
options WebSockets connection options.
Definition at line 72 of file WebSocketWriter.java.
References de.tavendo.autobahn.WebSocketOptions.getMaxFramePayloadSize(), de.tavendo.autobahn.WebSocketWriter.mBuffer, de.tavendo.autobahn.WebSocketWriter.mLooper, de.tavendo.autobahn.WebSocketWriter.mMaster, de.tavendo.autobahn.WebSocketWriter.mOptions, and de.tavendo.autobahn.WebSocketWriter.mSocket.
Member Function Documentation
void de.tavendo.autobahn.WebSocketWriter.forward (Object message)
Call this from the foreground (UI) thread to make the writer (running on background thread) send a WebSocket message on the underlying TCP.
Parameters:
message Message to send to WebSockets writer. An instance of the message classes inside WebSocketMessage or another type which then needs to be handled within processAppMessage() (in a class derived from this class).
Definition at line 96 of file WebSocketWriter.java.
Referenced by de.tavendo.autobahn.WampConnection.call(), de.tavendo.autobahn.WebSocketConnection.createHandler(), de.tavendo.autobahn.WampConnection.prefix(), de.tavendo.autobahn.WampConnection.publish(), de.tavendo.autobahn.WampConnection.subscribe(), and de.tavendo.autobahn.WampConnection.unsubscribe().
void de.tavendo.autobahn.WebSocketWriter.handleMessage (Message msg)
Process message received from foreground thread.
This is called from the message looper set up for the background thread running this writer.
Parameters:
msg Message from thread message queue.
Definition at line 375 of file WebSocketWriter.java.
References de.tavendo.autobahn.ByteBufferOutputStream.clear(), de.tavendo.autobahn.ByteBufferOutputStream.flip(), de.tavendo.autobahn.ByteBufferOutputStream.getBuffer(), de.tavendo.autobahn.WebSocketWriter.mBuffer, de.tavendo.autobahn.WebSocketWriter.mSocket, de.tavendo.autobahn.WebSocketWriter.notify(), de.tavendo.autobahn.WebSocketWriter.processMessage(), and de.tavendo.autobahn.ByteBufferOutputStream.remaining().
byte [] de.tavendo.autobahn.WebSocketWriter.newFrameMask () [private]
Create new (random) frame mask.
Returns:
Frame mask (4 octets).
Definition at line 134 of file WebSocketWriter.java.
References de.tavendo.autobahn.WebSocketWriter.mRng.
Referenced by de.tavendo.autobahn.WebSocketWriter.sendFrame().
String de.tavendo.autobahn.WebSocketWriter.newHandshakeKey () [private]
Create new key for WebSockets handshake.
Returns:
WebSockets handshake key (Base64 encoded).
Definition at line 122 of file WebSocketWriter.java.
References de.tavendo.autobahn.WebSocketWriter.mRng.
Referenced by de.tavendo.autobahn.WebSocketWriter.sendClientHandshake().
void de.tavendo.autobahn.WebSocketWriter.notify (Object message) [private]
Notify the master (foreground thread).
Parameters:
message Message to send to master.
Definition at line 109 of file WebSocketWriter.java.
References de.tavendo.autobahn.WebSocketWriter.mMaster.
Referenced by de.tavendo.autobahn.WebSocketWriter.handleMessage().
void de.tavendo.autobahn.WebSocketWriter.processAppMessage (Object msg) throws WebSocketException, IOException [protected]
Process message other than plain WebSockets or control message.
This is intended to be overridden in derived classes.
Parameters:
msg Message from foreground thread to process.
Reimplemented in de.tavendo.autobahn.WampWriter.
Definition at line 464 of file WebSocketWriter.java.
Referenced by de.tavendo.autobahn.WebSocketWriter.processMessage().
void de.tavendo.autobahn.WebSocketWriter.processMessage (Object msg) throws IOException, WebSocketException [protected]
Process WebSockets or control message from master.
Normally, there should be no reason to override this. If you do, you need to know what you are doing.
Parameters:
msg An instance of the message types within WebSocketMessage or a message that is handled in processAppMessage().
Definition at line 411 of file WebSocketWriter.java.
References de.tavendo.autobahn.WebSocketWriter.mLooper, de.tavendo.autobahn.WebSocketWriter.processAppMessage(), de.tavendo.autobahn.WebSocketWriter.sendBinaryMessage(), de.tavendo.autobahn.WebSocketWriter.sendClientHandshake(), de.tavendo.autobahn.WebSocketWriter.sendClose(), de.tavendo.autobahn.WebSocketWriter.sendPing(), de.tavendo.autobahn.WebSocketWriter.sendPong(), de.tavendo.autobahn.WebSocketWriter.sendRawTextMessage(), and de.tavendo.autobahn.WebSocketWriter.sendTextMessage().
Referenced by de.tavendo.autobahn.WebSocketWriter.handleMessage().
void de.tavendo.autobahn.WebSocketWriter.sendBinaryMessage (WebSocketMessage.BinaryMessage message) throws IOException, WebSocketException [private]
Send WebSockets binary message.
Definition at line 247 of file WebSocketWriter.java.
References de.tavendo.autobahn.WebSocketOptions.getMaxMessagePayloadSize(), de.tavendo.autobahn.WebSocketWriter.mOptions, and de.tavendo.autobahn.WebSocketWriter.sendFrame().
Referenced by de.tavendo.autobahn.WebSocketWriter.processMessage().
void de.tavendo.autobahn.WebSocketWriter.sendClientHandshake (WebSocketMessage.ClientHandshake message) throws IOException [private]
Send WebSocket client handshake.
Definition at line 144 of file WebSocketWriter.java.
References de.tavendo.autobahn.ByteBufferOutputStream.crlf(), de.tavendo.autobahn.WebSocketWriter.mBuffer, de.tavendo.autobahn.WebSocketWriter.newHandshakeKey(), and de.tavendo.autobahn.ByteBufferOutputStream.write().
Referenced by de.tavendo.autobahn.WebSocketWriter.processMessage().
void de.tavendo.autobahn.WebSocketWriter.sendClose (WebSocketMessage.Close message) throws IOException, WebSocketException [private]
Send WebSockets close.
Definition at line 189 of file WebSocketWriter.java.
References de.tavendo.autobahn.WebSocketWriter.sendFrame().
Referenced by de.tavendo.autobahn.WebSocketWriter.processMessage().
void de.tavendo.autobahn.WebSocketWriter.sendFrame (int opcode, boolean fin, byte[] payload) throws IOException [protected]
Sends a WebSockets frame.
Only need to use this method in derived classes which implement more message types in processAppMessage(). You need to know what you are doing!
Parameters:
opcode The WebSocket frame opcode.
fin FIN flag for WebSocket frame.
payload Frame payload or null.
Definition at line 286 of file WebSocketWriter.java.
Referenced by de.tavendo.autobahn.WampWriter.processAppMessage(), de.tavendo.autobahn.WebSocketWriter.sendBinaryMessage(), de.tavendo.autobahn.WebSocketWriter.sendClose(), de.tavendo.autobahn.WebSocketWriter.sendPing(), de.tavendo.autobahn.WebSocketWriter.sendPong(), de.tavendo.autobahn.WebSocketWriter.sendRawTextMessage(), and de.tavendo.autobahn.WebSocketWriter.sendTextMessage().
void de.tavendo.autobahn.WebSocketWriter.sendFrame (int opcode, boolean fin, byte[] payload, int offset, int length) throws IOException [protected]
Sends a WebSockets frame.
Only need to use this method in derived classes which implement more message types in processAppMessage(). You need to know what you are doing!
Parameters:
opcode The WebSocket frame opcode.
fin FIN flag for WebSocket frame.
payload Frame payload or null.
offset Offset within payload of the chunk to send.
length Length of the chunk within payload to send.
Todo:
optimize masking
Todo:
masking within buffer of output stream
Definition at line 305 of file WebSocketWriter.java.
References de.tavendo.autobahn.WebSocketOptions.getMaskClientFrames(), de.tavendo.autobahn.WebSocketWriter.mBuffer, de.tavendo.autobahn.WebSocketWriter.mOptions, de.tavendo.autobahn.WebSocketWriter.newFrameMask(), and de.tavendo.autobahn.ByteBufferOutputStream.write().
void de.tavendo.autobahn.WebSocketWriter.sendPing (WebSocketMessage.Ping message) throws IOException, WebSocketException [private]
Send WebSockets ping.
Definition at line 224 of file WebSocketWriter.java.
References de.tavendo.autobahn.WebSocketWriter.sendFrame().
Referenced by de.tavendo.autobahn.WebSocketWriter.processMessage().
void de.tavendo.autobahn.WebSocketWriter.sendPong (WebSocketMessage.Pong message) throws IOException, WebSocketException [private]
Send WebSockets pong.
Normally, unsolicited Pongs are not used, but Pongs are only send in response to a Ping from the peer.
Definition at line 236 of file WebSocketWriter.java.
References de.tavendo.autobahn.WebSocketWriter.sendFrame().
Referenced by de.tavendo.autobahn.WebSocketWriter.processMessage().
void de.tavendo.autobahn.WebSocketWriter.sendRawTextMessage (WebSocketMessage.RawTextMessage message) throws IOException, WebSocketException [private]
Send WebSockets binary message.
Definition at line 270 of file WebSocketWriter.java.
References de.tavendo.autobahn.WebSocketOptions.getMaxMessagePayloadSize(), de.tavendo.autobahn.WebSocketWriter.mOptions, and de.tavendo.autobahn.WebSocketWriter.sendFrame().
Referenced by de.tavendo.autobahn.WebSocketWriter.processMessage().
void de.tavendo.autobahn.WebSocketWriter.sendTextMessage (WebSocketMessage.TextMessage message) throws IOException, WebSocketException [private]
Send WebSockets text message.
Definition at line 258 of file WebSocketWriter.java.
References de.tavendo.autobahn.WebSocketOptions.getMaxMessagePayloadSize(), de.tavendo.autobahn.WebSocketWriter.mOptions, and de.tavendo.autobahn.WebSocketWriter.sendFrame().
Referenced by de.tavendo.autobahn.WebSocketWriter.processMessage().
Member Data Documentation
final ByteBufferOutputStream de.tavendo.autobahn.WebSocketWriter.mBuffer [private]
The send buffer that holds data to send on socket.
Definition at line 60 of file WebSocketWriter.java.
Referenced by de.tavendo.autobahn.WebSocketWriter.handleMessage(), de.tavendo.autobahn.WebSocketWriter.sendClientHandshake(), de.tavendo.autobahn.WebSocketWriter.sendFrame(), and de.tavendo.autobahn.WebSocketWriter.WebSocketWriter().
final Looper de.tavendo.autobahn.WebSocketWriter.mLooper [private]
Message looper this object is running on.
Definition at line 51 of file WebSocketWriter.java.
Referenced by de.tavendo.autobahn.WebSocketWriter.processMessage(), and de.tavendo.autobahn.WebSocketWriter.WebSocketWriter().
final Handler de.tavendo.autobahn.WebSocketWriter.mMaster [private]
Connection master.
Definition at line 48 of file WebSocketWriter.java.
Referenced by de.tavendo.autobahn.WebSocketWriter.notify(), and de.tavendo.autobahn.WebSocketWriter.WebSocketWriter().
final WebSocketOptions de.tavendo.autobahn.WebSocketWriter.mOptions [private]
WebSockets options.
Definition at line 57 of file WebSocketWriter.java.
Referenced by de.tavendo.autobahn.WebSocketWriter.sendBinaryMessage(), de.tavendo.autobahn.WebSocketWriter.sendFrame(), de.tavendo.autobahn.WebSocketWriter.sendRawTextMessage(), de.tavendo.autobahn.WebSocketWriter.sendTextMessage(), and de.tavendo.autobahn.WebSocketWriter.WebSocketWriter().
final Random de.tavendo.autobahn.WebSocketWriter.mRng = new Random() [private]
Random number generator for handshake key and frame mask generation.
Definition at line 45 of file WebSocketWriter.java.
Referenced by de.tavendo.autobahn.WebSocketWriter.newFrameMask(), and de.tavendo.autobahn.WebSocketWriter.newHandshakeKey().
final SocketChannel de.tavendo.autobahn.WebSocketWriter.mSocket [private]
The NIO socket channel created on foreground thread.
Definition at line 54 of file WebSocketWriter.java.
Referenced by de.tavendo.autobahn.WebSocketWriter.handleMessage(), and de.tavendo.autobahn.WebSocketWriter.WebSocketWriter().
The documentation for this class was generated from the following file:
src/de/tavendo/autobahn/WebSocketWriter.java