de.tavendo.autobahn.WebSocketReader Class Reference
de.tavendo.autobahn.WebSocketReader Class Reference
WebSocket reader, the receiving leg of a WebSockets connection.
Classes
class FrameHeader
WebSockets frame metadata.
Public Member Functions
WebSocketReader (Handler master, SocketChannel socket, WebSocketOptions options, String threadName)
Create new WebSockets background reader.
void quit ()
Graceful shutdown of background reader thread (called from master).
void run ()
Run the background reader thread loop.
Protected Member Functions
void notify (Object message)
Notify the master (foreground thread) of WebSockets message received and unwrapped.
void onHandshake ()
WebSockets handshake reply from server received, default notifies master.
void onClose (int code, String reason)
WebSockets close received, default notifies master.
void onPing (byte[] payload)
WebSockets ping received, default notifies master.
void onPong (byte[] payload)
WebSockets pong received, default notifies master.
void onTextMessage (String payload)
WebSockets text message received, default notifies master.
void onRawTextMessage (byte[] payload)
WebSockets text message received, default notifies master.
void onBinaryMessage (byte[] payload)
WebSockets binary message received, default notifies master.
Private Member Functions
boolean processData () throws Exception
Process incoming WebSockets data (after handshake).
boolean processHandshake () throws UnsupportedEncodingException
Process WebSockets handshake received from server.
boolean consumeData () throws Exception
Consume data buffered in mFrameBuffer.
Private Attributes
final Handler mMaster
final SocketChannel mSocket
final WebSocketOptions mOptions
final ByteBuffer mFrameBuffer
NoCopyByteArrayOutputStream mMessagePayload
boolean mStopped = false
int mState
boolean mInsideMessage = false
int mMessageOpcode
FrameHeader mFrameHeader
Frame currently being received.
Utf8Validator mUtf8Validator = new Utf8Validator()
Static Private Attributes
static final boolean DEBUG = true
static final String TAG = WebSocketReader.class.getName()
static final int STATE_CLOSED = 0
static final int STATE_CONNECTING = 1
static final int STATE_CLOSING = 2
static final int STATE_OPEN = 3
Detailed Description
WebSocket reader, the receiving leg of a WebSockets connection.
This runs on it's own background thread and posts messages to master thread's message queue for there to be consumed by the application. The only method that needs to be called (from foreground thread) is quit(), which gracefully shuts down the background receiver thread.
Definition at line 36 of file WebSocketReader.java.
Constructor & Destructor Documentation
de.tavendo.autobahn.WebSocketReader.WebSocketReader (Handler master, SocketChannel socket, WebSocketOptions options, String threadName)
Create new WebSockets background reader.
Parameters:
master The message handler of master (foreground thread).
socket The socket channel created on foreground thread.
Definition at line 86 of file WebSocketReader.java.
References de.tavendo.autobahn.WebSocketOptions.getMaxFramePayloadSize(), de.tavendo.autobahn.WebSocketOptions.getMaxMessagePayloadSize(), and de.tavendo.autobahn.WebSocketReader.mFrameHeader.
Member Function Documentation
boolean de.tavendo.autobahn.WebSocketReader.consumeData () throws Exception [private]
Consume data buffered in mFrameBuffer.
Definition at line 539 of file WebSocketReader.java.
References de.tavendo.autobahn.WebSocketReader.processData(), and de.tavendo.autobahn.WebSocketReader.processHandshake().
Referenced by de.tavendo.autobahn.WebSocketReader.run().
void de.tavendo.autobahn.WebSocketReader.notify (Object message) [protected]
Notify the master (foreground thread) of WebSockets message received and unwrapped.
Parameters:
message Message to send to master.
Definition at line 121 of file WebSocketReader.java.
Referenced by de.tavendo.autobahn.WampReader.onBinaryMessage(), de.tavendo.autobahn.WebSocketReader.onBinaryMessage(), de.tavendo.autobahn.WebSocketReader.onClose(), de.tavendo.autobahn.WebSocketReader.onHandshake(), de.tavendo.autobahn.WebSocketReader.onPing(), de.tavendo.autobahn.WebSocketReader.onPong(), de.tavendo.autobahn.WampReader.onRawTextMessage(), de.tavendo.autobahn.WebSocketReader.onRawTextMessage(), de.tavendo.autobahn.WampReader.onTextMessage(), de.tavendo.autobahn.WebSocketReader.onTextMessage(), and de.tavendo.autobahn.WebSocketReader.run().
void de.tavendo.autobahn.WebSocketReader.onBinaryMessage (byte[] payload) [protected]
WebSockets binary message received, default notifies master.
Parameters:
payload Binary message payload or null (empty payload).
Reimplemented in de.tavendo.autobahn.WampReader.
Definition at line 498 of file WebSocketReader.java.
References de.tavendo.autobahn.WebSocketReader.notify().
Referenced by de.tavendo.autobahn.WebSocketReader.processData().
void de.tavendo.autobahn.WebSocketReader.onClose (int code, String reason) [protected]
WebSockets close received, default notifies master.
Definition at line 437 of file WebSocketReader.java.
References de.tavendo.autobahn.WebSocketReader.notify().
Referenced by de.tavendo.autobahn.WebSocketReader.processData().
void de.tavendo.autobahn.WebSocketReader.onHandshake () [protected]
WebSockets handshake reply from server received, default notifies master.
Definition at line 428 of file WebSocketReader.java.
References de.tavendo.autobahn.WebSocketReader.notify().
Referenced by de.tavendo.autobahn.WebSocketReader.processHandshake().
void de.tavendo.autobahn.WebSocketReader.onPing (byte[] payload) [protected]
WebSockets ping received, default notifies master.
Parameters:
payload Ping payload or null.
Definition at line 448 of file WebSocketReader.java.
References de.tavendo.autobahn.WebSocketReader.notify().
Referenced by de.tavendo.autobahn.WebSocketReader.processData().
void de.tavendo.autobahn.WebSocketReader.onPong (byte[] payload) [protected]
WebSockets pong received, default notifies master.
Parameters:
payload Pong payload or null.
Definition at line 459 of file WebSocketReader.java.
References de.tavendo.autobahn.WebSocketReader.notify().
Referenced by de.tavendo.autobahn.WebSocketReader.processData().
void de.tavendo.autobahn.WebSocketReader.onRawTextMessage (byte[] payload) [protected]
WebSockets text message received, default notifies master.
This will only be called when the option receiveTextMessagesRaw HAS been set.
Parameters:
payload Text message payload as raw UTF-8 octets or null (empty payload).
Reimplemented in de.tavendo.autobahn.WampReader.
Definition at line 487 of file WebSocketReader.java.
References de.tavendo.autobahn.WebSocketReader.notify().
Referenced by de.tavendo.autobahn.WebSocketReader.processData().
void de.tavendo.autobahn.WebSocketReader.onTextMessage (String payload) [protected]
WebSockets text message received, default notifies master.
This will only be called when the option receiveTextMessagesRaw HAS NOT been set.
Parameters:
payload Text message payload as Java String decoded from raw UTF-8 payload or null (empty payload).
Reimplemented in de.tavendo.autobahn.WampReader.
Definition at line 473 of file WebSocketReader.java.
References de.tavendo.autobahn.WebSocketReader.notify().
Referenced by de.tavendo.autobahn.WebSocketReader.processData().
boolean de.tavendo.autobahn.WebSocketReader.processData () throws Exception [private]
Process incoming WebSockets data (after handshake).
Todo:
refactor this for streaming processing, incl. fail fast on invalid UTF-8 within frame already
Definition at line 132 of file WebSocketReader.java.
References de.tavendo.autobahn.WebSocketOptions.getMaxFramePayloadSize(), de.tavendo.autobahn.WebSocketOptions.getMaxMessagePayloadSize(), de.tavendo.autobahn.WebSocketOptions.getReceiveTextMessagesRaw(), de.tavendo.autobahn.WebSocketOptions.getValidateIncomingUtf8(), de.tavendo.autobahn.Utf8Validator.isValid(), de.tavendo.autobahn.WebSocketReader.mFrameHeader, de.tavendo.autobahn.WebSocketReader.onBinaryMessage(), de.tavendo.autobahn.WebSocketReader.onClose(), de.tavendo.autobahn.WebSocketReader.onPing(), de.tavendo.autobahn.WebSocketReader.onPong(), de.tavendo.autobahn.WebSocketReader.onRawTextMessage(), de.tavendo.autobahn.WebSocketReader.onTextMessage(), de.tavendo.autobahn.Utf8Validator.reset(), and de.tavendo.autobahn.Utf8Validator.validate().
Referenced by de.tavendo.autobahn.WebSocketReader.consumeData().
boolean de.tavendo.autobahn.WebSocketReader.processHandshake () throws UnsupportedEncodingException [private]
Process WebSockets handshake received from server.
Todo:
process & verify handshake from server
Todo:
forward subprotocol, if any
Definition at line 507 of file WebSocketReader.java.
References de.tavendo.autobahn.WebSocketReader.onHandshake().
Referenced by de.tavendo.autobahn.WebSocketReader.consumeData().
void de.tavendo.autobahn.WebSocketReader.quit ()
Graceful shutdown of background reader thread (called from master).
Definition at line 107 of file WebSocketReader.java.
void de.tavendo.autobahn.WebSocketReader.run ()
Run the background reader thread loop.
Definition at line 565 of file WebSocketReader.java.
References de.tavendo.autobahn.WebSocketReader.consumeData(), and de.tavendo.autobahn.WebSocketReader.notify().
Member Data Documentation
FrameHeader de.tavendo.autobahn.WebSocketReader.mFrameHeader [private]
Frame currently being received.
Definition at line 60 of file WebSocketReader.java.
Referenced by de.tavendo.autobahn.WebSocketReader.processData(), and de.tavendo.autobahn.WebSocketReader.WebSocketReader().
The documentation for this class was generated from the following file:
src/de/tavendo/autobahn/WebSocketReader.java