de.tavendo.autobahn.Utf8Validator Class Reference
de.tavendo.autobahn.Utf8Validator Class Reference
Incremental UTF-8 validator.
Public Member Functions
Utf8Validator ()
Create new incremental UTF-8 validator.
void reset ()
Reset validator state to begin validation of new UTF-8 stream.
int position ()
Get end of validated position within stream.
boolean isValid ()
Check if incremental validation (currently) has ended on a complete encoded Unicode codepoint.
boolean validate (byte[] data, int off, int len)
Validate a chunk of octets for UTF-8.
boolean validate (byte[] data)
Validate a chunk of octets for UTF-8.
Private Attributes
int mState
int mPos
Static Private Attributes
static final int[] DFA
DFA state transitions (14 x 32 = 448).
static final int ACCEPT = 0
static final int REJECT = 1
Detailed Description
Incremental UTF-8 validator.
The validator runs with constant memory consumption (minimal state). Purpose is to validate UTF-8, not to decode (which could be done easily also, but we rely on Java built in facilities for that).
Implements the algorithm "Flexible and Economical UTF-8 Decoder" by Bjoern Hoehrmann (http://bjoern.hoehrmann.de/utf-8/decoder/dfa/).
Definition at line 34 of file Utf8Validator.java.
Constructor & Destructor Documentation
de.tavendo.autobahn.Utf8Validator.Utf8Validator ()
Create new incremental UTF-8 validator.
The validator is already resetted and thus immediately usable.
Definition at line 64 of file Utf8Validator.java.
References de.tavendo.autobahn.Utf8Validator.reset().
Member Function Documentation
boolean de.tavendo.autobahn.Utf8Validator.isValid ()
Check if incremental validation (currently) has ended on a complete encoded Unicode codepoint.
Returns:
True, iff currently ended on codepoint.
Definition at line 95 of file Utf8Validator.java.
Referenced by de.tavendo.autobahn.WebSocketReader.processData().
int de.tavendo.autobahn.Utf8Validator.position ()
Get end of validated position within stream.
When validate() returns false, indicating an UTF-8 error, this function can be used to get the exact position within the stream upon which the violation was encountered.
Returns:
Current position with stream validated.
Definition at line 85 of file Utf8Validator.java.
void de.tavendo.autobahn.Utf8Validator.reset ()
Reset validator state to begin validation of new UTF-8 stream.
Definition at line 72 of file Utf8Validator.java.
Referenced by de.tavendo.autobahn.WebSocketReader.processData(), and de.tavendo.autobahn.Utf8Validator.Utf8Validator().
boolean de.tavendo.autobahn.Utf8Validator.validate (byte[] data, int off, int len)
Validate a chunk of octets for UTF-8.
Parameters:
data Buffer which contains chunk to validate.
off Offset within buffer where to continue with validation.
len Length in octets to validate within buffer.
Returns:
False as soon as UTF-8 violation occurs, true otherwise.
Definition at line 107 of file Utf8Validator.java.
References de.tavendo.autobahn.Utf8Validator.DFA.
Referenced by de.tavendo.autobahn.WebSocketReader.processData(), and de.tavendo.autobahn.Utf8Validator.validate().
boolean de.tavendo.autobahn.Utf8Validator.validate (byte[] data)
Validate a chunk of octets for UTF-8.
Parameters:
data Buffer which contains chunk to validate.
Returns:
False as soon as UTF-8 violation occurs, true otherwise.
Definition at line 125 of file Utf8Validator.java.
References de.tavendo.autobahn.Utf8Validator.validate().
Member Data Documentation
final int [] de.tavendo.autobahn.Utf8Validator.DFA [static, private]
Initial value:
 {
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,
      7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
      8,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
      0xa,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x4,0x3,0x3,
      0xb,0x6,0x6,0x6,0x5,0x8,0x8,0x8,0x8,0x8,0x8,0x8,0x8,0x8,0x8,0x8,
      0x0,0x1,0x2,0x3,0x5,0x8,0x7,0x1,0x1,0x1,0x4,0x6,0x1,0x1,0x1,0x1,
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,1,0,1,1,1,1,1,1,
      1,2,1,1,1,1,1,2,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,
      1,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,3,1,1,1,1,1,1,
      1,3,1,1,1,1,1,3,1,3,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1
   }
DFA state transitions (14 x 32 = 448).
Definition at line 37 of file Utf8Validator.java.
Referenced by de.tavendo.autobahn.Utf8Validator.validate().
The documentation for this class was generated from the following file:
src/de/tavendo/autobahn/Utf8Validator.java