de.tavendo.autobahn.ByteBufferOutputStream Class Reference
de.tavendo.autobahn.ByteBufferOutputStream Class Reference
OutputStream wrapping a ByteBuffer.
Inherits OutputStream.
Public Member Functions
ByteBufferOutputStream ()
Create a direct allocated ByteBuffer wrapped as OutputStream.
ByteBufferOutputStream (int initialSize, int growSize)
Create a direct allocated ByteBuffer wrapped as OutputStream.
ByteBuffer getBuffer ()
Get the underlying ByteBuffer.
Buffer flip ()
Calls flip on the underyling ByteBuffer.
Buffer clear ()
Calls clear on the underlying ByteBuffer.
int remaining ()
Calls remaining() on underlying ByteBuffer.
synchronized void expand (int requestSize)
Expand the underlying ByteBuffer and preserve content.
synchronized void write (int b) throws IOException
Write one byte to the underlying ByteBuffer via this OutputStream.
synchronized void write (byte[] bytes, int off, int len) throws IOException
Write a chunk of bytes to the underyling ByteBuffer via this OutputStream.
synchronized void write (byte[] bytes) throws IOException
Write a complete byte array to the underlying ByteBuffer via this OutputStream.
synchronized void write (String str) throws IOException
Write the UTF-8 encoding of a String to the underlying ByteBuffer via this OutputStream.
synchronized void crlf () throws IOException
Write CR-LF.
Private Attributes
final int mInitialSize
Initial size of allocated ByteBuffer.
final int mGrowSize
Amount to grow when ByteBuffer needs to be enlarged.
ByteBuffer mBuffer
Internal ByteBuffer wrapped.
Detailed Description
OutputStream wrapping a ByteBuffer.
This class internally allocates a direct ByteBuffer for use i.e. with NIO for socket I/O. The ByteBuffer is automatically enlarged if needed (preserving contents when enlarged).
Definition at line 31 of file ByteBufferOutputStream.java.
Constructor & Destructor Documentation
de.tavendo.autobahn.ByteBufferOutputStream.ByteBufferOutputStream ()
Create a direct allocated ByteBuffer wrapped as OutputStream.
Definition at line 45 of file ByteBufferOutputStream.java.
de.tavendo.autobahn.ByteBufferOutputStream.ByteBufferOutputStream (int initialSize, int growSize)
Create a direct allocated ByteBuffer wrapped as OutputStream.
Parameters:
initialSize Initial size of ByteBuffer.
growSize When buffer needs to grow, enlarge by this amount.
Definition at line 55 of file ByteBufferOutputStream.java.
References de.tavendo.autobahn.ByteBufferOutputStream.mBuffer, de.tavendo.autobahn.ByteBufferOutputStream.mGrowSize, and de.tavendo.autobahn.ByteBufferOutputStream.mInitialSize.
Member Function Documentation
Buffer de.tavendo.autobahn.ByteBufferOutputStream.clear ()
Calls clear on the underlying ByteBuffer.
Definition at line 81 of file ByteBufferOutputStream.java.
References de.tavendo.autobahn.ByteBufferOutputStream.mBuffer.
Referenced by de.tavendo.autobahn.WebSocketWriter.handleMessage().
synchronized void de.tavendo.autobahn.ByteBufferOutputStream.crlf () throws IOException
Write CR-LF.
Exceptions:
IOException
Definition at line 171 of file ByteBufferOutputStream.java.
References de.tavendo.autobahn.ByteBufferOutputStream.write().
Referenced by de.tavendo.autobahn.WebSocketWriter.sendClientHandshake().
synchronized void de.tavendo.autobahn.ByteBufferOutputStream.expand (int requestSize)
Expand the underlying ByteBuffer and preserve content.
Parameters:
requestSize Requested new size.
Definition at line 97 of file ByteBufferOutputStream.java.
References de.tavendo.autobahn.ByteBufferOutputStream.mBuffer, and de.tavendo.autobahn.ByteBufferOutputStream.mGrowSize.
Referenced by de.tavendo.autobahn.ByteBufferOutputStream.write().
Buffer de.tavendo.autobahn.ByteBufferOutputStream.flip ()
Calls flip on the underyling ByteBuffer.
Definition at line 74 of file ByteBufferOutputStream.java.
References de.tavendo.autobahn.ByteBufferOutputStream.mBuffer.
Referenced by de.tavendo.autobahn.WebSocketWriter.handleMessage().
ByteBuffer de.tavendo.autobahn.ByteBufferOutputStream.getBuffer ()
Get the underlying ByteBuffer.
Returns:
ByteBuffer underlying this OutputStream.
Definition at line 67 of file ByteBufferOutputStream.java.
References de.tavendo.autobahn.ByteBufferOutputStream.mBuffer.
Referenced by de.tavendo.autobahn.WebSocketWriter.handleMessage().
int de.tavendo.autobahn.ByteBufferOutputStream.remaining ()
Calls remaining() on underlying ByteBuffer.
Definition at line 88 of file ByteBufferOutputStream.java.
References de.tavendo.autobahn.ByteBufferOutputStream.mBuffer.
Referenced by de.tavendo.autobahn.WebSocketWriter.handleMessage().
synchronized void de.tavendo.autobahn.ByteBufferOutputStream.write (int b) throws IOException
Write one byte to the underlying ByteBuffer via this OutputStream.
Parameters:
b Byte to be written.
Definition at line 118 of file ByteBufferOutputStream.java.
References de.tavendo.autobahn.ByteBufferOutputStream.expand(), and de.tavendo.autobahn.ByteBufferOutputStream.mBuffer.
Referenced by de.tavendo.autobahn.ByteBufferOutputStream.crlf(), de.tavendo.autobahn.WebSocketWriter.sendClientHandshake(), de.tavendo.autobahn.WebSocketWriter.sendFrame(), and de.tavendo.autobahn.ByteBufferOutputStream.write().
synchronized void de.tavendo.autobahn.ByteBufferOutputStream.write (byte[] bytes, int off, int len) throws IOException
Write a chunk of bytes to the underyling ByteBuffer via this OutputStream.
Parameters:
bytes Write bytes from this byte array.
off Start reading at this offset within byte array.
len Write this many bytes, and enlarge underyling ByteBuffer when necessary, preserving the contents.
Definition at line 136 of file ByteBufferOutputStream.java.
References de.tavendo.autobahn.ByteBufferOutputStream.expand(), and de.tavendo.autobahn.ByteBufferOutputStream.mBuffer.
synchronized void de.tavendo.autobahn.ByteBufferOutputStream.write (byte[] bytes) throws IOException
Write a complete byte array to the underlying ByteBuffer via this OutputStream.
Parameters:
bytes Byte array to be written.
Definition at line 151 of file ByteBufferOutputStream.java.
References de.tavendo.autobahn.ByteBufferOutputStream.write().
synchronized void de.tavendo.autobahn.ByteBufferOutputStream.write (String str) throws IOException
Write the UTF-8 encoding of a String to the underlying ByteBuffer via this OutputStream.
Parameters:
str String to be written.
Exceptions:
IOException
Definition at line 162 of file ByteBufferOutputStream.java.
References de.tavendo.autobahn.ByteBufferOutputStream.write().
Member Data Documentation
ByteBuffer de.tavendo.autobahn.ByteBufferOutputStream.mBuffer [private]
Internal ByteBuffer wrapped.
Definition at line 40 of file ByteBufferOutputStream.java.
Referenced by de.tavendo.autobahn.ByteBufferOutputStream.ByteBufferOutputStream(), de.tavendo.autobahn.ByteBufferOutputStream.clear(), de.tavendo.autobahn.ByteBufferOutputStream.expand(), de.tavendo.autobahn.ByteBufferOutputStream.flip(), de.tavendo.autobahn.ByteBufferOutputStream.getBuffer(), de.tavendo.autobahn.ByteBufferOutputStream.remaining(), and de.tavendo.autobahn.ByteBufferOutputStream.write().
final int de.tavendo.autobahn.ByteBufferOutputStream.mGrowSize [private]
Amount to grow when ByteBuffer needs to be enlarged.
Definition at line 37 of file ByteBufferOutputStream.java.
Referenced by de.tavendo.autobahn.ByteBufferOutputStream.ByteBufferOutputStream(), and de.tavendo.autobahn.ByteBufferOutputStream.expand().
final int de.tavendo.autobahn.ByteBufferOutputStream.mInitialSize [private]
Initial size of allocated ByteBuffer.
Definition at line 34 of file ByteBufferOutputStream.java.
Referenced by de.tavendo.autobahn.ByteBufferOutputStream.ByteBufferOutputStream().
The documentation for this class was generated from the following file:
src/de/tavendo/autobahn/ByteBufferOutputStream.java