de.tavendo.autobahn.WebSocketOptions Class Reference
de.tavendo.autobahn.WebSocketOptions Class Reference
WebSockets connection options.
Public Member Functions
WebSocketOptions ()
Construct default options.
WebSocketOptions (WebSocketOptions other)
Construct options as copy from other options object.
void setReceiveTextMessagesRaw (boolean enabled)
Receive text message as raw byte array with verified, but non-decoded UTF-8.
boolean getReceiveTextMessagesRaw ()
When true, WebSockets text messages are provided as verified, but non-decoded UTF-8 in byte arrays.
void setMaxFramePayloadSize (int size)
Set maximum frame payload size that will be accepted when receiving.
int getMaxFramePayloadSize ()
Get maxium frame payload size that will be accepted when receiving.
void setMaxMessagePayloadSize (int size)
Set maximum message payload size (after reassembly of fragmented messages) that will be accepted when receiving.
int getMaxMessagePayloadSize ()
Get maximum message payload size (after reassembly of fragmented messages) that will be accepted when receiving.
void setTcpNoDelay (boolean enabled)
Set TCP No-Delay ("Nagle") for TCP connection.
boolean getTcpNoDelay ()
Get TCP No-Delay ("Nagle") for TCP connection.
void setSocketReceiveTimeout (int timeoutMs)
Set receive timeout on socket.
int getSocketReceiveTimeout ()
Get socket receive timeout.
void setSocketConnectTimeout (int timeoutMs)
Set connect timeout on socket.
int getSocketConnectTimeout ()
Get socket connect timeout.
void setValidateIncomingUtf8 (boolean enabled)
Controls whether incoming text message payload is verified to be valid UTF-8.
boolean getValidateIncomingUtf8 ()
Get UTF-8 validation option.
void setMaskClientFrames (boolean enabled)
Controls whether to mask client-to-server WebSocket frames.
boolean getMaskClientFrames ()
Get mask client frames option.
Private Attributes
int mMaxFramePayloadSize
int mMaxMessagePayloadSize
boolean mReceiveTextMessagesRaw
boolean mTcpNoDelay
int mSocketReceiveTimeout
int mSocketConnectTimeout
boolean mValidateIncomingUtf8
boolean mMaskClientFrames
Detailed Description
WebSockets connection options.
This can be supplied to WebSocketConnection in connect(). Note that the latter copies the options provided to connect(), so any change after connect will have no effect.
Definition at line 28 of file WebSocketOptions.java.
Constructor & Destructor Documentation
de.tavendo.autobahn.WebSocketOptions.WebSocketOptions ()
Construct default options.
Definition at line 43 of file WebSocketOptions.java.
de.tavendo.autobahn.WebSocketOptions.WebSocketOptions (WebSocketOptions other)
Construct options as copy from other options object.
Parameters:
other Options to copy.
Definition at line 60 of file WebSocketOptions.java.
Member Function Documentation
boolean de.tavendo.autobahn.WebSocketOptions.getMaskClientFrames ()
Get mask client frames option.
Returns:
True, iff client-to-server frames are masked.
Definition at line 254 of file WebSocketOptions.java.
Referenced by de.tavendo.autobahn.WebSocketWriter.sendFrame().
int de.tavendo.autobahn.WebSocketOptions.getMaxFramePayloadSize ()
Get maxium frame payload size that will be accepted when receiving.
Returns:
Maximum size in octets for frame payload.
Definition at line 117 of file WebSocketOptions.java.
Referenced by de.tavendo.autobahn.WebSocketReader.processData(), de.tavendo.autobahn.WebSocketReader.WebSocketReader(), and de.tavendo.autobahn.WebSocketWriter.WebSocketWriter().
int de.tavendo.autobahn.WebSocketOptions.getMaxMessagePayloadSize ()
Get maximum message payload size (after reassembly of fragmented messages) that will be accepted when receiving.
Returns:
Maximum size in octets for message payload.
Definition at line 144 of file WebSocketOptions.java.
Referenced by de.tavendo.autobahn.WebSocketReader.processData(), de.tavendo.autobahn.WebSocketWriter.sendBinaryMessage(), de.tavendo.autobahn.WebSocketWriter.sendRawTextMessage(), de.tavendo.autobahn.WebSocketWriter.sendTextMessage(), and de.tavendo.autobahn.WebSocketReader.WebSocketReader().
boolean de.tavendo.autobahn.WebSocketOptions.getReceiveTextMessagesRaw ()
When true, WebSockets text messages are provided as verified, but non-decoded UTF-8 in byte arrays.
Returns:
True, iff option is enabled.
Definition at line 90 of file WebSocketOptions.java.
Referenced by de.tavendo.autobahn.WebSocketReader.processData().
int de.tavendo.autobahn.WebSocketOptions.getSocketConnectTimeout ()
Get socket connect timeout.
Returns:
Socket receive timeout in ms.
Definition at line 211 of file WebSocketOptions.java.
int de.tavendo.autobahn.WebSocketOptions.getSocketReceiveTimeout ()
Get socket receive timeout.
Returns:
Socket receive timeout in ms.
Definition at line 187 of file WebSocketOptions.java.
boolean de.tavendo.autobahn.WebSocketOptions.getTcpNoDelay ()
Get TCP No-Delay ("Nagle") for TCP connection.
Returns:
True, iff TCP No-Delay is enabled.
Definition at line 164 of file WebSocketOptions.java.
boolean de.tavendo.autobahn.WebSocketOptions.getValidateIncomingUtf8 ()
Get UTF-8 validation option.
Returns:
True, iff incoming UTF-8 is validated.
Definition at line 232 of file WebSocketOptions.java.
Referenced by de.tavendo.autobahn.WebSocketReader.processData().
void de.tavendo.autobahn.WebSocketOptions.setMaskClientFrames (boolean enabled)
Controls whether to mask client-to-server WebSocket frames.
Beware, normally, WebSockets servers will deny non-masked c2s frames and fail the connection.
DEFAULT: true
Parameters:
enabled Set true to mask client-to-server frames.
Definition at line 245 of file WebSocketOptions.java.
void de.tavendo.autobahn.WebSocketOptions.setMaxFramePayloadSize (int size)
Set maximum frame payload size that will be accepted when receiving.
DEFAULT: 4MB
Parameters:
size Maximum size in octets for frame payload.
Definition at line 102 of file WebSocketOptions.java.
void de.tavendo.autobahn.WebSocketOptions.setMaxMessagePayloadSize (int size)
Set maximum message payload size (after reassembly of fragmented messages) that will be accepted when receiving.
DEFAULT: 4MB
Parameters:
size Maximum size in octets for message payload.
Definition at line 129 of file WebSocketOptions.java.
void de.tavendo.autobahn.WebSocketOptions.setReceiveTextMessagesRaw (boolean enabled)
Receive text message as raw byte array with verified, but non-decoded UTF-8.
DEFAULT: false
Parameters:
enabled True to enable.
Definition at line 80 of file WebSocketOptions.java.
void de.tavendo.autobahn.WebSocketOptions.setSocketConnectTimeout (int timeoutMs)
Set connect timeout on socket.
When a WebSocket connection is about to be established, the TCP socket connect will timeout after this period.
DEFAULT: 3000
Parameters:
timeoutMs Socket connect timeout in ms.
Definition at line 200 of file WebSocketOptions.java.
void de.tavendo.autobahn.WebSocketOptions.setSocketReceiveTimeout (int timeoutMs)
Set receive timeout on socket.
When the TCP connection disappears, that will only be recognized by the reader after this timeout.
DEFAULT: 200
Parameters:
timeoutMs Socket receive timeout in ms.
Definition at line 176 of file WebSocketOptions.java.
void de.tavendo.autobahn.WebSocketOptions.setTcpNoDelay (boolean enabled)
Set TCP No-Delay ("Nagle") for TCP connection.
DEFAULT: true
Parameters:
enabled True to enable TCP No-Delay.
Definition at line 155 of file WebSocketOptions.java.
void de.tavendo.autobahn.WebSocketOptions.setValidateIncomingUtf8 (boolean enabled)
Controls whether incoming text message payload is verified to be valid UTF-8.
DEFAULT: true
Parameters:
enabled True to verify incoming UTF-8.
Definition at line 223 of file WebSocketOptions.java.
The documentation for this class was generated from the following file:
src/de/tavendo/autobahn/WebSocketOptions.java