de.tavendo.autobahn.PrefixMap Class Reference
de.tavendo.autobahn.PrefixMap Class Reference
Mapping between CURIEs and URIs.
Public Member Functions
void set (String prefix, String uri)
Set mapping of prefix to URI.
String get (String prefix)
Returns the URI for the prefix or None if prefix has no mapped URI.
String remove (String prefix)
Remove mapping of prefix to URI.
void clear ()
Remove all prefix mappings.
String resolve (String curie)
Resolve given CURIE to full URI.
String resolveOrPass (String curieOrUri)
Resolve given CURIE/URI and return string verbatim if cannot be resolved.
String shrink (String uri)
Shrink given URI to CURIE.
Private Attributes
final HashMap< String, String > mPrefixes = new HashMap<String, String>()
final HashMap< String, String > mUris = new HashMap<String, String>()
Detailed Description
Mapping between CURIEs and URIs.
Provides a two-way mapping between CURIEs (Compact URI Expressions) and full URIs.
See also:
http://www.w3.org/TR/curie/
Todo:
Prefixes MUST be NCNames (http://www.w3.org/TR/1999/REC-xml-names-19990114/#NT-NCName)
Todo:
Work in the details of http://www.w3.org/TR/curie/ (default prefixes, ..)
Definition at line 34 of file PrefixMap.java.
Member Function Documentation
void de.tavendo.autobahn.PrefixMap.clear ()
Remove all prefix mappings.
Definition at line 82 of file PrefixMap.java.
Referenced by de.tavendo.autobahn.WampConnection.connect().
String de.tavendo.autobahn.PrefixMap.get (String prefix)
Returns the URI for the prefix or None if prefix has no mapped URI.
Parameters:
prefix Prefix to look up.
Returns:
Mapped URI for prefix or None.
Definition at line 56 of file PrefixMap.java.
Referenced by de.tavendo.autobahn.WampConnection.prefix().
String de.tavendo.autobahn.PrefixMap.remove (String prefix)
Remove mapping of prefix to URI.
Parameters:
prefix Prefix for which mapping should be removed.
Returns:
The URI the prefix was mapped to (when removed), or null when prefix is unmapped (so there wasn't anything to remove).
Definition at line 68 of file PrefixMap.java.
String de.tavendo.autobahn.PrefixMap.resolve (String curie)
Resolve given CURIE to full URI.
Parameters:
curie CURIE (i.e. "rdf:label").
Returns:
Full URI for CURIE or None.
Definition at line 93 of file PrefixMap.java.
Referenced by de.tavendo.autobahn.PrefixMap.resolveOrPass().
String de.tavendo.autobahn.PrefixMap.resolveOrPass (String curieOrUri)
Resolve given CURIE/URI and return string verbatim if cannot be resolved.
Parameters:
curieOrUri CURIE or URI.
Returns:
Full URI for CURIE or original string.
Definition at line 110 of file PrefixMap.java.
References de.tavendo.autobahn.PrefixMap.resolve().
Referenced by de.tavendo.autobahn.WampConnection.subscribe().
void de.tavendo.autobahn.PrefixMap.set (String prefix, String uri)
Set mapping of prefix to URI.
Parameters:
prefix Prefix to be mapped.
uri URI the prefix is to be mapped to.
Definition at line 45 of file PrefixMap.java.
Referenced by de.tavendo.autobahn.WampConnection.prefix().
String de.tavendo.autobahn.PrefixMap.shrink (String uri)
Shrink given URI to CURIE.
If no appropriate prefix mapping is available, return original URI.
Parameters:
uri URI to shrink.
Returns:
CURIE or original URI.
Definition at line 127 of file PrefixMap.java.
Referenced by de.tavendo.autobahn.WampConnection.publish(), and de.tavendo.autobahn.WampConnection.subscribe().
The documentation for this class was generated from the following file:
src/de/tavendo/autobahn/PrefixMap.java